name: Build and deploy Next.js app to Azure - streamflix-movies

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'

      - name: Install dependencies
        working-directory: ./streamflix
        run: npm ci

      - name: Build Next.js application
        working-directory: ./streamflix
        run: npm run build

      - name: Upload application
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ./streamflix

  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download application
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: ./streamflix

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2802D022449F4229BC4CC9D5B47B7C50 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A541883E52314288A270B01E5CACF099 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_71C07CB2C810431EBD6D486C6AD05916 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: streamflix-movies
          slot-name: Production
          package: ./streamflix

      - name: Logout from Azure
        run: az logout
